const { VALID_SITES } = require("../data/siteConfig");
const service = require("../services/packingListReportService");
const isAdmin = (user) => user?.role === "admin" || user?.isAdmin;
const resolveSite = (req) => { const site = isAdmin(req.user) ? String(req.query.site || "") : String(req.user?.site || ""); if (!VALID_SITES.includes(site)) throw Object.assign(new Error("Selecciona una sede valida."), { statusCode: 400 }); return site; };
const fail = (res, error) => res.status(error.statusCode || 500).json({ message: error.statusCode ? error.message : "No se pudo generar el reporte." });
const listCustomers = async (req, res) => { try { const site = resolveSite(req); res.json({ site, customers: await service.getCustomersForSite(site) }); } catch (error) { fail(res, error); } };
const listPeriods = async (req, res) => { try { const site = resolveSite(req); const periods = await service.getAvailablePeriods({ site, customer: req.query.customer }); res.json({ site, customer: req.query.customer, periods }); } catch (error) { fail(res, error); } };
const downloadMonthlyReport = async (req, res) => { try { const report = await service.getMonthlyReportData({ site: resolveSite(req), customer: req.query.customer, month: req.query.month, year: req.query.year }); if (!report.fileCount || !report.rows.length) return res.status(404).json({ message: "No hay Packing Lists enviados para los filtros seleccionados." }); const pdf = await service.generateMonthlyReportPdf(report); const customer = report.customer.replace(/[^a-zA-Z0-9_-]+/g, "_").slice(0, 50); res.set({ "Content-Type": "application/pdf", "Content-Disposition": `attachment; filename="packing-list-${customer}-${report.year}-${String(report.month).padStart(2, "0")}.pdf"`, "Content-Length": pdf.length }); res.send(pdf); } catch (error) { fail(res, error); } };
module.exports = { listCustomers, listPeriods, downloadMonthlyReport };
